### ISSUE TITLE
Incorrect ovs path in build script

### ISSUE THREAD

**Issue by shawnsschen** [xsited/ssg#1]
On line 778 of the build_ovs_dpdk.sh, it checks if ovs-2.4.0 exists. If so, the ovs src path is set.
But the decompressed source directory should be openvswitch-2.4.0, not openvswitch-2.4.0.tar.gz.
Currently, the script terminates after dpdk is compiled. After revising the path, ovs can be compiled successfully as well.
Could you fix this?

**Comment by xsited** [comment]
sorry for the delay.  adjustment made.
